chore: add cancel action to linter

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,6 +39,12 @@ jobs:
 
       - name: Run linter
         run: yarn lint
+      - run: |
+          echo 'I am failing'
+          exit 1
+      - name: Cancelling parallel jobs if current job failed
+        if: failure()
+        uses: andymckay/cancel-action@0.2
 
   test:
     runs-on: ${{ matrix.os }}
